### ISSUE TITLE
Astronaut's hitbox is too big

### ISSUE THREAD

**Issue by pawap90** [pawap90/space-commit#41]
The current size of the hitbox makes it easy to lose by hitting an enemy even when it doesn't look like you are colliding with it, which is frustrating.

It can be resized in the `AstronautCharacter` class by using `this.body.setSize()` and `this.body.offset.x`.

**Comment by justinhhorner** [comment]
Hello!

I'd like to work on this issue. 🚀

**Comment by pawap90** [comment]
Hi Justin!

Great. go for it!
