### ISSUE TITLE
change Right - Forward, left - Backward

### ISSUE THREAD

**Issue by FOSS-Love** [pawap90/space-commit#45]
Not a big thing but 'forward' and 'backward' makes more sense.

**Comment by pawap90** [comment]
I was looking at the project and couldn't find out what you mean. Would you please add more detail?

**Comment by FOSS-Love** [comment]
Yes sure,

The instructions says 'Move left with A' and 'Move right with D', instead
it could say something like, 'Move backward with A' and 'Move forward with right'

**Comment by pawap90** [comment]
Oh I see! Ok, that sounds good! 

So, for anyone interested in submitting a PR for this issue: It would be a change on the control's instructions located in the `public/index.html` file.
